name: Deploy Frontend
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run tests in Docker container
        run: docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.SECRET_ACCESS_KEY }}
          application_name: frontend
          environment_name: Frontend-dev
          existing_bucket_name: elasticbeanstalk-us-east-2-526802959187
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip